# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
  - task: DockerCompose@0
    displayName: Build images
    inputs:
      containerregistrytype: 'Container Registry'
      dockerRegistryEndpoint: 'DockerHub'
      dockerComposeFile: 'docker-compose.yml'
      action: 'Build services'
      includeLatestTag: true
  - task: DockerCompose@0
    displayName: Push images
    inputs:
      containerregistrytype: 'Container Registry'
      dockerRegistryEndpoint: 'DockerHub'
      dockerComposeFile: 'docker-compose.yml'
      action: 'Push services'
      includeLatestTag: true
  - task: CopyFiles@2
    displayName: Copy docker-compose to staging
    inputs:
      Contents: 'docker-compose.yml'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'
      OverWrite: true
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'
      publishLocation: 'Container'