version: '3.7'

services: 
  react-app:
    build: ./react-app
    ports:
    - 3000:3000
    environment:
      CHOKIDAR_USEPOLLING: "true"
    volumes:
    - /usr/src/app/node_modules
    - ./react-app:/app
    stdin_open: true
