version: '3.7'

services: 
  react-app:
    image: myreactregistry.azurecr.io/react-app:latest
    container_name: react-app
    build: 
      context: react-app
      dockerfile: NoNginx.Dockerfile
  nginx: 
    image: myreactregistry.azurecr.io/nginx-react
    container_name: nginx
    build: nginx
    ports:
    - 80:80
    # volumes:
    # - /nginx.conf /etc/nginx/conf.d/default.conf