version: '3.7'

services: 
  react-app:
    image: philitician/react-app:latest
    container_name: react-app
  nginx: 
    image: philitician/nginx-react
    container_name: nginx
    ports:
    - 80:80
    # volumes:
    # - /nginx.conf /etc/nginx/conf.d/default.conf